# Generated by Django 2.2.2 on 2019-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfav_app', '0002_auto_20190610_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('image_url', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
