# Generated by Django 2.2.2 on 2019-06-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamfav_app', '0003_owteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rival_Team',
        ),
    ]
